### PR TITLE
Specify pefix

### PR DESCRIPTION
**Pull request by kirisaki**
#12

### CODE REVIEW

**Comment by miminashi** [comment]
@kirisaki Please disclose how to try this change.

**Comment by kirisaki** [comment]
`cargo run` describes usage. And `cargo run /dev/ttyACM` specifies a prefix.

**Comment by miminashi** [comment]
I think `<PREFIX>` needs to be explained.
(No problem in this pull request. Let's add a issue for it)

```
mmns2020:~/projects/greptty (specify-path) $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/greptty`
error: The following required arguments were not provided:
    <PREFIX>

USAGE:
    greptty <PREFIX>

For more information try --help
```

**Comment by miminashi** [comment]
@kirisaki Did you try `./examples/detect_co2.sh` ? This is the only substitute for testing at the moment.

I tried it and found a problem on the example script.
I already fixed it and pushed to this pull request.
Please git pull and try `./examples/detect_co2.sh /dev/ttyACM`.

NOTICE: Please be sure to connect 2 different types of devices.

If it works, you can see such following outputs.

```
$ ./examples/detect_co2.sh /dev/cu.usbmodem
CO2 device found: /dev/cu.usbmodem14401
baud rate: 9600
co2=410;status=0
co2=410;status=0
co2=410;status=0
co2=410;status=0
co2=410;status=0
co2=410;status=0
co2=410;status=0
^C
```

If you've checked if it works on your local machine too, I'll approve this pull request.

Thanks.

**Comment by kirisaki** [comment]
It worked!

**Review by miminashi — APPROVED** [review]

**Pull request merged**
