### PR TITLE
Minimum requirement

### PR DESCRIPTION
**Pull request by kirisaki**

### CODE REVIEW

**Comment by miminashi** [comment]
@kirisaki Please add the build instruction to the README.md

**Comment by kirisaki** [comment]
> @kirisaki Please add the build instruction to the README.md

OK, but it should be done another branch.

**Comment by kirisaki** [comment]
No, it should be done in this PR. I will do so.

**Review by miminashi — APPROVED** [review]
I've temporarily fixed the path and confirmed that I can run it on the mac.

**Pull request merged**
